[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
ryvo_protocol = "GNZ4upG1xGRGxXUUNtKgRqFtfvNQ3JCWXr1FFj51HedJ"
mock_yield = "916FRevu6HadFHTDi8hV5tCXmJiJDTbADJRx5hQjKDcD"

[programs.localnet]
ryvo_protocol = "GNZ4upG1xGRGxXUUNtKgRqFtfvNQ3JCWXr1FFj51HedJ"
mock_yield = "916FRevu6HadFHTDi8hV5tCXmJiJDTbADJRx5hQjKDcD"

[programs.mainnet]
ryvo_protocol = "GNZ4upG1xGRGxXUUNtKgRqFtfvNQ3JCWXr1FFj51HedJ"
mock_yield = "916FRevu6HadFHTDi8hV5tCXmJiJDTbADJRx5hQjKDcD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/home/heis/ryvo/ryvo-protocol/keys/devnet-deployer.json"

[scripts]
test = "npm run test:shared"
