// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:9e1f6a7c1ef13bd8
use anchor_lang::prelude::*;

#[error_code]
pub enum AgonWithdrawalsPilotError {
    TokenNotFound = 0,
    AmountMustBePositive = 1,
    InsufficientBalance = 2,
    WithdrawalAlreadyPending = 3,
    NoWithdrawalPending = 4,
    WithdrawalLocked = 5,
    InvalidTokenDecimals = 6,
    MathOverflow = 7,
}
// ---- END GENERATED ----
