// ---- GENERATED BY QEDGEN — DO NOT EDIT — regenerated from .qedspec ----
//! Per-handler guard checks derived from the `.qedspec`.
//! Called from user-owned `instructions/<name>::handler` before
//! business logic; keep guard logic here, policy-free logic there.

#![allow(unused_variables, unused_imports, dead_code, clippy::too_many_arguments)]

use anchor_lang::prelude::*;
use crate::errors::*;
use crate::instructions::*;

/// Guards for `deposit`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn deposit(ctx: &mut Deposit, token: u16, amount: u64) -> Result<(), ProgramError> {
    // requires: token = s.token_id
    if !(token == s.token_id) { return Err(ProgramError::from(AgonWithdrawalsPilotError::TokenNotFound)); }
    // requires: s.token_registered
    if !(s.token_registered) { return Err(ProgramError::from(AgonWithdrawalsPilotError::TokenNotFound)); }
    // requires: amount > 0
    if !(amount > 0) { return Err(ProgramError::from(AgonWithdrawalsPilotError::AmountMustBePositive)); }
    // requires: s.wallet_balance ≥ amount
    if !(s.wallet_balance >= amount) { return Err(ProgramError::from(AgonWithdrawalsPilotError::InsufficientBalance)); }
    // requires: s.vault_balance + amount ≤ 18446744073709551615
    if !(s.vault_balance + amount <= 18446744073709551615) { return Err(ProgramError::from(AgonWithdrawalsPilotError::MathOverflow)); }
    // requires: s.available_balance + amount ≤ 18446744073709551615
    if !(s.available_balance + amount <= 18446744073709551615) { return Err(ProgramError::from(AgonWithdrawalsPilotError::MathOverflow)); }
    Ok(())
}

/// Guards for `request_withdrawal`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn request_withdrawal(ctx: &mut RequestWithdrawal, token: u16, amount: u64, destination: Address) -> Result<(), ProgramError> {
    // requires: token = s.token_id
    if !(token == s.token_id) { return Err(ProgramError::from(AgonWithdrawalsPilotError::TokenNotFound)); }
    // requires: s.token_registered
    if !(s.token_registered) { return Err(ProgramError::from(AgonWithdrawalsPilotError::TokenNotFound)); }
    // requires: amount > 0
    if !(amount > 0) { return Err(ProgramError::from(AgonWithdrawalsPilotError::AmountMustBePositive)); }
    // requires: s.available_balance ≥ amount
    if !(s.available_balance >= amount) { return Err(ProgramError::from(AgonWithdrawalsPilotError::InsufficientBalance)); }
    // requires: s.withdrawing_balance = 0
    if !(s.withdrawing_balance == 0) { return Err(ProgramError::from(AgonWithdrawalsPilotError::WithdrawalAlreadyPending)); }
    // requires: s.now + s.configured_timelock ≤ 18446744073709551615
    if !(s.now + s.configured_timelock <= 18446744073709551615) { return Err(ProgramError::from(AgonWithdrawalsPilotError::MathOverflow)); }
    // requires: s.withdrawing_balance + amount ≤ 18446744073709551615
    if !(s.withdrawing_balance + amount <= 18446744073709551615) { return Err(ProgramError::from(AgonWithdrawalsPilotError::MathOverflow)); }
    Ok(())
}

/// Guards for `cancel_withdrawal`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn cancel_withdrawal(ctx: &mut CancelWithdrawal, token: u16) -> Result<(), ProgramError> {
    // requires: token = s.token_id
    if !(token == s.token_id) { return Err(ProgramError::from(AgonWithdrawalsPilotError::TokenNotFound)); }
    // requires: s.withdrawing_balance > 0
    if !(s.withdrawing_balance > 0) { return Err(ProgramError::from(AgonWithdrawalsPilotError::NoWithdrawalPending)); }
    // requires: s.available_balance + s.withdrawing_balance ≤ 18446744073709551615
    if !(s.available_balance + s.withdrawing_balance <= 18446744073709551615) { return Err(ProgramError::from(AgonWithdrawalsPilotError::MathOverflow)); }
    Ok(())
}

/// Guards for `execute_withdrawal_timelocked_case_0`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn execute_withdrawal_timelocked_case_0(ctx: &mut ExecuteWithdrawalTimelockedCase0, token: u16) -> Result<(), ProgramError> {
    // requires: token = s.token_id
    if !(token == s.token_id) { return Err(ProgramError::from(AgonWithdrawalsPilotError::TokenNotFound)); }
    // requires: s.token_registered
    if !(s.token_registered) { return Err(ProgramError::from(AgonWithdrawalsPilotError::TokenNotFound)); }
    // requires: s.token_decimals ≤ 20
    if !(s.token_decimals <= 20) { return Err(ProgramError::from(AgonWithdrawalsPilotError::InvalidTokenDecimals)); }
    // requires: s.withdrawing_balance > 0
    if !(s.withdrawing_balance > 0) { return Err(ProgramError::from(AgonWithdrawalsPilotError::NoWithdrawalPending)); }
    // requires: s.now ≥ s.withdrawal_unlock_at
    if !(s.now >= s.withdrawal_unlock_at) { return Err(ProgramError::from(AgonWithdrawalsPilotError::WithdrawalLocked)); }
    // requires: s.vault_balance ≥ s.withdrawing_balance
    if !(s.vault_balance >= s.withdrawing_balance) { return Err(ProgramError::from(AgonWithdrawalsPilotError::InsufficientBalance)); }
    // requires: s.configured_fee_bps = 0
    if !(s.configured_fee_bps == 0) { return Err(ProgramError::from(AgonWithdrawalsPilotError::MathOverflow)); }
    // requires: s.min_fee_native_units > 0
    if !(s.min_fee_native_units > 0) { return Err(ProgramError::from(AgonWithdrawalsPilotError::MathOverflow)); }
    // requires: s.fee_recipient_balance + s.withdrawing_balance ≤ 18446744073709551615
    if !(s.fee_recipient_balance + s.withdrawing_balance <= 18446744073709551615) { return Err(ProgramError::from(AgonWithdrawalsPilotError::MathOverflow)); }
    // requires: s.fee_recipient_balance + ((let fee := (((s.withdrawing_balance) * (s.configured_fee_bps)) / (10000)); fee)) ≤ 18446744073709551615
    if !(s.fee_recipient_balance + (({ let fee = mul_div_floor_u128(s.withdrawing_balance, s.configured_fee_bps, 10000); fee })) <= 18446744073709551615) { return Err(ProgramError::from(AgonWithdrawalsPilotError::MathOverflow)); }
    // requires: s.destination_balance + ((let fee := (((s.withdrawing_balance) * (s.configured_fee_bps)) / (10000)); s.withdrawing_balance - fee)) ≤ 18446744073709551615
    if !(s.destination_balance + (({ let fee = mul_div_floor_u128(s.withdrawing_balance, s.configured_fee_bps, 10000); s.withdrawing_balance - fee })) <= 18446744073709551615) { return Err(ProgramError::from(AgonWithdrawalsPilotError::MathOverflow)); }
    // requires: s.fee_recipient_balance + s.min_fee_native_units ≤ 18446744073709551615
    if !(s.fee_recipient_balance + s.min_fee_native_units <= 18446744073709551615) { return Err(ProgramError::from(AgonWithdrawalsPilotError::MathOverflow)); }
    // requires: s.destination_balance + s.withdrawing_balance - s.min_fee_native_units ≤ 18446744073709551615
    if !(s.destination_balance + s.withdrawing_balance - s.min_fee_native_units <= 18446744073709551615) { return Err(ProgramError::from(AgonWithdrawalsPilotError::MathOverflow)); }
    // requires: s.withdrawing_balance ≤ s.min_fee_native_units
    debug_assert!(s.withdrawing_balance <= s.min_fee_native_units);
    Ok(())
}

/// Guards for `execute_withdrawal_timelocked_case_1`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn execute_withdrawal_timelocked_case_1(ctx: &mut ExecuteWithdrawalTimelockedCase1, token: u16) -> Result<(), ProgramError> {
    // requires: token = s.token_id
    if !(token == s.token_id) { return Err(ProgramError::from(AgonWithdrawalsPilotError::TokenNotFound)); }
    // requires: s.token_registered
    if !(s.token_registered) { return Err(ProgramError::from(AgonWithdrawalsPilotError::TokenNotFound)); }
    // requires: s.token_decimals ≤ 20
    if !(s.token_decimals <= 20) { return Err(ProgramError::from(AgonWithdrawalsPilotError::InvalidTokenDecimals)); }
    // requires: s.withdrawing_balance > 0
    if !(s.withdrawing_balance > 0) { return Err(ProgramError::from(AgonWithdrawalsPilotError::NoWithdrawalPending)); }
    // requires: s.now ≥ s.withdrawal_unlock_at
    if !(s.now >= s.withdrawal_unlock_at) { return Err(ProgramError::from(AgonWithdrawalsPilotError::WithdrawalLocked)); }
    // requires: s.vault_balance ≥ s.withdrawing_balance
    if !(s.vault_balance >= s.withdrawing_balance) { return Err(ProgramError::from(AgonWithdrawalsPilotError::InsufficientBalance)); }
    // requires: s.configured_fee_bps = 0
    if !(s.configured_fee_bps == 0) { return Err(ProgramError::from(AgonWithdrawalsPilotError::MathOverflow)); }
    // requires: s.min_fee_native_units > 0
    if !(s.min_fee_native_units > 0) { return Err(ProgramError::from(AgonWithdrawalsPilotError::MathOverflow)); }
    // requires: s.fee_recipient_balance + s.withdrawing_balance ≤ 18446744073709551615
    if !(s.fee_recipient_balance + s.withdrawing_balance <= 18446744073709551615) { return Err(ProgramError::from(AgonWithdrawalsPilotError::MathOverflow)); }
    // requires: s.fee_recipient_balance + ((let fee := (((s.withdrawing_balance) * (s.configured_fee_bps)) / (10000)); fee)) ≤ 18446744073709551615
    if !(s.fee_recipient_balance + (({ let fee = mul_div_floor_u128(s.withdrawing_balance, s.configured_fee_bps, 10000); fee })) <= 18446744073709551615) { return Err(ProgramError::from(AgonWithdrawalsPilotError::MathOverflow)); }
    // requires: s.destination_balance + ((let fee := (((s.withdrawing_balance) * (s.configured_fee_bps)) / (10000)); s.withdrawing_balance - fee)) ≤ 18446744073709551615
    if !(s.destination_balance + (({ let fee = mul_div_floor_u128(s.withdrawing_balance, s.configured_fee_bps, 10000); s.withdrawing_balance - fee })) <= 18446744073709551615) { return Err(ProgramError::from(AgonWithdrawalsPilotError::MathOverflow)); }
    // requires: s.fee_recipient_balance + s.min_fee_native_units ≤ 18446744073709551615
    if !(s.fee_recipient_balance + s.min_fee_native_units <= 18446744073709551615) { return Err(ProgramError::from(AgonWithdrawalsPilotError::MathOverflow)); }
    // requires: s.destination_balance + s.withdrawing_balance - s.min_fee_native_units ≤ 18446744073709551615
    if !(s.destination_balance + s.withdrawing_balance - s.min_fee_native_units <= 18446744073709551615) { return Err(ProgramError::from(AgonWithdrawalsPilotError::MathOverflow)); }
    // requires: ¬(s.withdrawing_balance ≤ s.min_fee_native_units)
    debug_assert!(!(s.withdrawing_balance <= s.min_fee_native_units));
    // requires: (((s.withdrawing_balance) * (s.configured_fee_bps)) / (10000)) ≥ s.min_fee_native_units
    debug_assert!(mul_div_floor_u128(s.withdrawing_balance, s.configured_fee_bps, 10000) >= s.min_fee_native_units);
    Ok(())
}

/// Guards for `execute_withdrawal_timelocked_otherwise`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn execute_withdrawal_timelocked_otherwise(ctx: &mut ExecuteWithdrawalTimelockedOtherwise, token: u16) -> Result<(), ProgramError> {
    // requires: token = s.token_id
    if !(token == s.token_id) { return Err(ProgramError::from(AgonWithdrawalsPilotError::TokenNotFound)); }
    // requires: s.token_registered
    if !(s.token_registered) { return Err(ProgramError::from(AgonWithdrawalsPilotError::TokenNotFound)); }
    // requires: s.token_decimals ≤ 20
    if !(s.token_decimals <= 20) { return Err(ProgramError::from(AgonWithdrawalsPilotError::InvalidTokenDecimals)); }
    // requires: s.withdrawing_balance > 0
    if !(s.withdrawing_balance > 0) { return Err(ProgramError::from(AgonWithdrawalsPilotError::NoWithdrawalPending)); }
    // requires: s.now ≥ s.withdrawal_unlock_at
    if !(s.now >= s.withdrawal_unlock_at) { return Err(ProgramError::from(AgonWithdrawalsPilotError::WithdrawalLocked)); }
    // requires: s.vault_balance ≥ s.withdrawing_balance
    if !(s.vault_balance >= s.withdrawing_balance) { return Err(ProgramError::from(AgonWithdrawalsPilotError::InsufficientBalance)); }
    // requires: s.configured_fee_bps = 0
    if !(s.configured_fee_bps == 0) { return Err(ProgramError::from(AgonWithdrawalsPilotError::MathOverflow)); }
    // requires: s.min_fee_native_units > 0
    if !(s.min_fee_native_units > 0) { return Err(ProgramError::from(AgonWithdrawalsPilotError::MathOverflow)); }
    // requires: s.fee_recipient_balance + s.withdrawing_balance ≤ 18446744073709551615
    if !(s.fee_recipient_balance + s.withdrawing_balance <= 18446744073709551615) { return Err(ProgramError::from(AgonWithdrawalsPilotError::MathOverflow)); }
    // requires: s.fee_recipient_balance + ((let fee := (((s.withdrawing_balance) * (s.configured_fee_bps)) / (10000)); fee)) ≤ 18446744073709551615
    if !(s.fee_recipient_balance + (({ let fee = mul_div_floor_u128(s.withdrawing_balance, s.configured_fee_bps, 10000); fee })) <= 18446744073709551615) { return Err(ProgramError::from(AgonWithdrawalsPilotError::MathOverflow)); }
    // requires: s.destination_balance + ((let fee := (((s.withdrawing_balance) * (s.configured_fee_bps)) / (10000)); s.withdrawing_balance - fee)) ≤ 18446744073709551615
    if !(s.destination_balance + (({ let fee = mul_div_floor_u128(s.withdrawing_balance, s.configured_fee_bps, 10000); s.withdrawing_balance - fee })) <= 18446744073709551615) { return Err(ProgramError::from(AgonWithdrawalsPilotError::MathOverflow)); }
    // requires: s.fee_recipient_balance + s.min_fee_native_units ≤ 18446744073709551615
    if !(s.fee_recipient_balance + s.min_fee_native_units <= 18446744073709551615) { return Err(ProgramError::from(AgonWithdrawalsPilotError::MathOverflow)); }
    // requires: s.destination_balance + s.withdrawing_balance - s.min_fee_native_units ≤ 18446744073709551615
    if !(s.destination_balance + s.withdrawing_balance - s.min_fee_native_units <= 18446744073709551615) { return Err(ProgramError::from(AgonWithdrawalsPilotError::MathOverflow)); }
    // requires: ¬(s.withdrawing_balance ≤ s.min_fee_native_units)
    debug_assert!(!(s.withdrawing_balance <= s.min_fee_native_units));
    // requires: ¬((((s.withdrawing_balance) * (s.configured_fee_bps)) / (10000)) ≥ s.min_fee_native_units)
    debug_assert!(!(mul_div_floor_u128(s.withdrawing_balance, s.configured_fee_bps, 10000) >= s.min_fee_native_units));
    Ok(())
}

// ---- END GENERATED ----
