// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:5afbb1e1a5a83b3e
#![no_std]

use anchor_lang::prelude::*;

mod instructions;
use instructions::*;
pub mod errors;
pub mod state;
pub mod guards;

declare_id!("DE4vmRRDu1EBj98pD9AuZmdTPFAyDChMmRoPRscze5g");

#[program]
mod agonwithdrawalspilot {
    use super::*;

    #[instruction(discriminator = 0)]
    pub fn deposit(ctx: Ctx<Deposit>, token: u16, amount: u64) -> Result<(), ProgramError> {
        ctx.accounts.handler(token, amount)
    }

    #[instruction(discriminator = 1)]
    pub fn request_withdrawal(ctx: Ctx<RequestWithdrawal>, token: u16, amount: u64, destination: Address) -> Result<(), ProgramError> {
        ctx.accounts.handler(token, amount, destination)
    }

    #[instruction(discriminator = 2)]
    pub fn cancel_withdrawal(ctx: Ctx<CancelWithdrawal>, token: u16) -> Result<(), ProgramError> {
        ctx.accounts.handler(token)
    }

    #[instruction(discriminator = 3)]
    pub fn execute_withdrawal_timelocked_case_0(ctx: Ctx<ExecuteWithdrawalTimelockedCase0>, token: u16) -> Result<(), ProgramError> {
        ctx.accounts.handler(token)
    }

    #[instruction(discriminator = 4)]
    pub fn execute_withdrawal_timelocked_case_1(ctx: Ctx<ExecuteWithdrawalTimelockedCase1>, token: u16) -> Result<(), ProgramError> {
        ctx.accounts.handler(token)
    }

    #[instruction(discriminator = 5)]
    pub fn execute_withdrawal_timelocked_otherwise(ctx: Ctx<ExecuteWithdrawalTimelockedOtherwise>, token: u16) -> Result<(), ProgramError> {
        ctx.accounts.handler(token)
    }

}
// ---- END GENERATED ----
