// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:e3d6b66a8d8fe2cc
use anchor_lang::prelude::*;

#[account(discriminator = 1, set_inner)]
pub struct AgonWithdrawalsPilotAccount {
    pub owner: Address,
    pub wallet_balance: u64,
    pub destination_balance: u64,
    pub vault_balance: u64,
    pub fee_recipient_balance: u64,
    pub available_balance: u64,
    pub withdrawing_balance: u64,
    pub withdrawal_unlock_at: u64,
    pub configured_timelock: u64,
    pub configured_fee_bps: u16,
    pub min_fee_native_units: u64,
    pub token_id: u16,
    pub token_decimals: u8,
    pub token_registered: bool,
    pub now: u64,
    pub physical_tokens_total: u64,
}

/// Program lifecycle states.
#[derive(Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum Status {
    Active = 0,
}
// ---- END GENERATED ----
